name: AppleLeadership
favicon: null
layout_spectrum: 0.75348
typography_spectrum: 0.38751
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Thoughts on the Leadership at Apple
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b2b2b'
    - '#dd1b1a'
    - '#838383'
    - '#ec7b7b'
  brandStrength: 0.375
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
