name: AppleLeadership
favicon: null
layout_spectrum: 0.75348
typography_spectrum: 0.38751
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Thoughts on the Leadership at Apple
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#556370'
    - '#c54d57'
    - '#c7f464'
    - '#4dcdc4'
    - '#e2b369'
  brandStrength: 0.8039742
  lightness: 0.6374866
  saturation: 0.9316465
  rhythmicContrast: 0.8748657
purpose: []
